version:  "3"

services:
  azure-sql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    hostname: walks-azure-sql
    cap_add: [ 'SYS_PTRACE' ]
    environment:
      ACCEPT_EULA: 1
      MSSQL_SA_PASSWORD: "Start123!"
      MSSQL_USER: "sa"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - ./.docker/mssql:/var/opt/mssql
