version:  "3"

services:
  azure-sql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    hostname: walks-azure-sql
    cap_add: [ 'SYS_PTRACE' ]
    environment:
      ACCEPT_EULA: 1
      MSSQL_SA_PASSWORD: "Start123!"
      MSSQL_USER: "sa"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - ./.docker/mssql:/var/opt/mssql

# services:
#   mssql:
#     image: mcr.microsoft.com/azure-sql-edge:latest
#     cap_add: [ 'SYS_PTRACE' ]
#     environment:
#       - "ACCEPT_EULA=1"
#       - "MSSQL_SA_PASSWORD=SU2orange!"
#     ports:
#       - "1433:1433"
#     hostname: mssql
#     volumes:
#       - "mssql-azuresql-edge-data:/var/opt/mssql"
#     networks:
#       - "learndb_net"
